/**
 * Local data layer — reads data.json generated by scripts/build-data.mjs.
 * Replaces Supabase queries for companies and problems in local-mode operation.
 */

export interface LocalCompany {
  id: number;
  name: string;
  problem_count: number;
}

export interface LocalProblem {
  id: number;
  title: string;
  url: string;
  difficulty: string | null;
  acceptance: number | null;
  frequency: number | null;
  problem_tags: Array<{ tag: string }>;
  company_problems: Array<{
    company: { id: number; name: string };
    timeframe_tag: string | null;
  }>;
}

interface DataFile {
  companies: LocalCompany[];
  problems: LocalProblem[];
}

// Module-level singleton so the JSON is only fetched once per page load
let cached: DataFile | null = null;
let loadPromise: Promise<DataFile> | null = null;

async function loadData(): Promise<DataFile> {
  if (cached) return cached;
  if (loadPromise) return loadPromise;

  const base = import.meta.env.BASE_URL;
  const url = (base.endsWith("/") ? base : base + "/") + "data.json";
  console.log("[localData] fetching", url);

  loadPromise = fetch(url)
    .then((r) => {
      if (!r.ok) throw new Error(`Failed to load data.json: ${r.status} (url: ${url})`);
      return r.json() as Promise<DataFile>;
    })
    .then((data) => {
      console.log(`[localData] loaded ${data.companies.length} companies, ${data.problems.length} problems`);
      cached = data;
      return data;
    })
    .catch((err) => {
      loadPromise = null; // allow retry
      throw err;
    });

  return loadPromise;
}

/** Returns all problems in the shape expected by AllProblems.tsx */
export async function fetchAllProblems(): Promise<LocalProblem[]> {
  const data = await loadData();
  return data.problems;
}

/**
 * Returns problems for a given company in the shape expected by CompanyProblems.tsx:
 * { timeframe_tag, problem: LocalProblem }
 */
export async function fetchCompanyProblems(companyId: number) {
  const data = await loadData();
  return data.problems
    .filter((p) => p.company_problems.some((cp) => cp.company.id === companyId))
    .map((p) => ({
      timeframe_tag:
        p.company_problems.find((cp) => cp.company.id === companyId)
          ?.timeframe_tag ?? null,
      problem: p,
    }));
}

export async function getCompanyById(
  companyId: number,
): Promise<LocalCompany | null> {
  const data = await loadData();
  return data.companies.find((c) => c.id === companyId) ?? null;
}

export async function searchCompanies(query: string): Promise<LocalCompany[]> {
  const data = await loadData();
  const lower = query.toLowerCase();
  return data.companies
    .filter((c) => c.name.toLowerCase().includes(lower))
    .sort((a, b) => a.name.localeCompare(b.name))
    .slice(0, 8);
}

export async function getStats(): Promise<{
  companies: number;
  problems: number;
}> {
  const data = await loadData();
  return { companies: data.companies.length, problems: data.problems.length };
}
